// layout component in next js. modify as needed
import { Inter } from "next/font/google";
import Appbar from "./Components/Appbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className="bg-[#000721] flex flex-col items-center">
                <Appbar />
                <div className="absolute w-full top-0 ">{children}</div>
            </body>
        </html>
    );
}
